name: jsipfs
version: git
summary: JavaScript implementation of the IPFS specification
description: |
  The JavaScript implementation of the IPFS protocol.
grade: stable
confinement: strict

apps:
  jsipfs:
    command: snapcraft-preload jsipfs
    plugs:
      - network
      - network-bind

parts:
  jsipfs:
    plugin: nodejs
    node-engine: 8.9.1
    source: .
    build-packages: [make, g++, python]
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages: [g++-multilib]
